name: splashpage
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.11
  - cookiecutter
  # Dependencies of jinja-markdown:
  - jinja2>=2.11
  - pygments>=2.6.1
  - pymdown-extensions>=7.1
  - pip:
    - jinja-markdown==1.210911
